# -*- coding: utf-8 -*-
# 리포트 허브(목차 페이지) 생성기 — reports.json 기반으로 index.html 생성
import json, html

d = json.load(open('/home/admin/report-hub/reports.json'))
reports = d['reports']

def esc(s): return html.escape(str(s))

cards = ""
for r in sorted(reports, key=lambda x: x['date'], reverse=True):
    cards += f'''
<div class="card">
  <div class="chead">
    <h2>{esc(r['title'])}</h2>
    <span class="date">📅 {esc(r['date'])}</span>
  </div>
  <p class="desc">{esc(r['desc'])}</p>
  <div class="actions">
    <a class="btn open" href="{esc(r['url'])}" target="_blank">리포트 열기 ↗</a>
    <a class="btn ghost" href="https://github.com/{esc(r['repo'])}" target="_blank">저장소</a>
    <a class="btn ghost" href="https://github.com/{esc(r['repo'])}/settings#danger-zone" target="_blank">직접 삭제</a>
  </div>
  <div class="manage">🔧 수정·삭제는 텔레그램으로 요청 (확인 후 처리) · 주소: <code>{esc(r['url'])}</code></div>
</div>'''

empty = '''<div class="empty">등록된 리포트가 없습니다.</div>''' if not reports else ''

page = f'''<!DOCTYPE html>
<html lang="ko"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex,nofollow">
<title>리포트 허브</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.min.css">
<style>
*{{box-sizing:border-box;margin:0;padding:0}}
body{{font-family:'Pretendard Variable',Pretendard,sans-serif;background:#0f1117;color:#e7e9ee;line-height:1.6}}
.wrap{{max-width:760px;margin:0 auto;padding:24px 16px 80px}}
header{{text-align:center;padding:38px 0 10px}}
h1{{font-size:26px;font-weight:800}} header p{{color:#8b90a0;font-size:13.5px;margin-top:8px}}
.policy{{background:#171a24;border:1px solid #262b3a;border-radius:12px;padding:13px 16px;font-size:13px;color:#a9aec0;margin:18px 0 26px}}
.policy b{{color:#c4b5fd}}
.meta{{display:flex;justify-content:space-between;font-size:12.5px;color:#6b7180;margin:0 4px 12px}}
.card{{background:#171a24;border:1px solid #262b3a;border-radius:16px;padding:20px 22px;margin-bottom:16px}}
.chead{{display:flex;justify-content:space-between;align-items:center;gap:10px}}
h2{{font-size:17px;font-weight:700}}
.date{{background:#211d33;color:#c4b5fd;border-radius:14px;padding:3px 12px;font-size:12px;font-weight:600;white-space:nowrap}}
.desc{{font-size:13.5px;color:#a9aec0;margin:10px 0 14px}}
.actions{{display:flex;gap:8px;flex-wrap:wrap}}
.btn{{text-decoration:none;border-radius:10px;padding:8px 16px;font-size:13px;font-weight:700}}
.open{{background:linear-gradient(135deg,#7c3aed,#db2777);color:#fff}}
.ghost{{background:#222636;color:#a9aec0;border:1px solid #31374b}}
.manage{{margin-top:12px;font-size:12px;color:#6b7180;border-top:1px solid #222636;padding-top:10px}}
code{{background:#222636;border-radius:5px;padding:1px 7px;font-size:11px;color:#8b90a0}}
.empty{{text-align:center;color:#6b7180;padding:50px 0}}
.foot{{text-align:center;font-size:11.5px;color:#4a4f60;margin-top:40px}}
</style></head><body>
<div class="wrap">
<header><h1>📂 리포트 허브</h1><p>생성된 모든 리포트의 목차 · 관리 페이지</p></header>
<div class="policy">📌 <b>운영 정책:</b> 새 리포트 요청 시 항상 <b>새 주소</b>로 생성됩니다 (기존 것 절대 덮어쓰기 없음). 특정 리포트 수정을 원하면 그 리포트를 콕 집어서 요청해 주세요. 수정·삭제는 텔레그램에서 요청하면 확인 후 처리됩니다.</div>
<div class="meta"><span>총 {len(reports)}건</span><span>최근 갱신: {esc(d['updated'])}</span></div>
{cards}{empty}
<div class="foot">Generated by OpenClaw · 주소 아는 사람만 접근 가능 (검색엔진 차단)</div>
</div></body></html>'''

open('/home/admin/report-hub/index.html','w').write(page)
print("허브 생성 완료:", len(page), "bytes,", len(reports), "건")
